[2024-04-10 11:38:48,190] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 11:38:48] "DELETE /pendencia?nome=Vazamento%20de%20√≥leo%20do%20equipamento%201 HTTP/1.1" 200 - - call_trace=/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 11:38:51,171] WARNING del_produto() L137  Erro ao deletar pendenica #'Vazamento de √≥leo do equipamento 1', pendencia n√£o encontrado na base :/ - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/app.py L137 
[2024-04-10 11:38:51,171] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 11:38:51] "[33mDELETE /pendencia?nome=Vazamento%20de%20√≥leo%20do%20equipamento%201 HTTP/1.1[0m" 404 - - call_trace=/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 11:38:51,797] WARNING del_produto() L137  Erro ao deletar pendenica #'Vazamento de √≥leo do equipamento 1', pendencia n√£o encontrado na base :/ - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/app.py L137 
[2024-04-10 11:38:51,798] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 11:38:51] "[33mDELETE /pendencia?nome=Vazamento%20de%20√≥leo%20do%20equipamento%201 HTTP/1.1[0m" 404 - - call_trace=/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 11:38:52,261] WARNING del_produto() L137  Erro ao deletar pendenica #'Vazamento de √≥leo do equipamento 1', pendencia n√£o encontrado na base :/ - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/app.py L137 
[2024-04-10 11:38:52,261] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 11:38:52] "[33mDELETE /pendencia?nome=Vazamento%20de%20√≥leo%20do%20equipamento%201 HTTP/1.1[0m" 404 - - call_trace=/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 11:38:53,065] WARNING del_produto() L137  Erro ao deletar pendenica #'Vazamento de √≥leo do equipamento 1', pendencia n√£o encontrado na base :/ - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/app.py L137 
[2024-04-10 11:38:53,066] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 11:38:53] "[33mDELETE /pendencia?nome=Vazamento%20de%20√≥leo%20do%20equipamento%201 HTTP/1.1[0m" 404 - - call_trace=/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 11:39:10,587] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 11:39:10] "DELETE /pendencia?nome=Vazamento%20de%20√≥leo%20do%20equipamento%202 HTTP/1.1" 200 - - call_trace=/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 11:39:11,385] WARNING del_produto() L137  Erro ao deletar pendenica #'Vazamento de √≥leo do equipamento 2', pendencia n√£o encontrado na base :/ - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/app.py L137 
[2024-04-10 11:39:11,386] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 11:39:11] "[33mDELETE /pendencia?nome=Vazamento%20de%20√≥leo%20do%20equipamento%202 HTTP/1.1[0m" 404 - - call_trace=/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 11:39:12,061] WARNING del_produto() L137  Erro ao deletar pendenica #'Vazamento de √≥leo do equipamento 2', pendencia n√£o encontrado na base :/ - call_trace=/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/app.py L137 
[2024-04-10 11:39:12,062] INFO _log() L96   127.0.0.1 - - [10/Apr/2024 11:39:12] "[33mDELETE /pendencia?nome=Vazamento%20de%20√≥leo%20do%20equipamento%202 HTTP/1.1[0m" 404 - - call_trace=/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/werkzeug/_internal.py L96  
[2024-04-10 11:39:38,882] INFO _log() L96    * Detected change in '/Users/pedroteixeira/Documents/PUCRJ/MVP3/meu_app_api/model/pendencia.py', reloading - call_trace=/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/werkzeug/_internal.py L96  
